### ISSUE TITLE
Crash when running aFileChooser.

### ISSUE THREAD

**Issue by fishnet37222** [iPaulPro/aFileChooser#16]
Hello,

I get the exception and stack trace linked below whenever I run the aFileChooserExample project on my Nexus 7.  I'm not sure why it's happening.

http://pastebin.com/CYFv4dV0

**Comment by carlosnavas** [comment]
Try this: 
1. Project -> Properties -> Order & Export and verify that "Android Private Libraries" is checked for both, library and android project. 
2. Clean all projects.
3. Try again.

**Comment by fishnet37222** [comment]
Thank you.  That solved it.
