### ISSUE TITLE
Feature Request: Choose directory 

### ISSUE THREAD

**Issue by dipendrapkrl** [iPaulPro/aFileChooser#24]
The app is really nice. One more feature that is missing is being able to choose directory.
Regards,

**Comment by patricks** [comment]
I also would love this feature.

**Comment by ravenfeld** [comment]
You can test my dev
https://github.com/ravenfeld/aFileChooser

**Comment by jasonzhang2022** [comment]
Still can not figure out how to select a directory. Can you give an example in wiki or code?

**Comment by ravenfeld** [comment]
if you use my code:
 Intent intent = new Intent(this, FileChooserActivity.class);
    intent.putExtra(FileChooserActivity.EXTRA_SELECT_FOLDER, true);

**Comment by jasonzhang2022** [comment]
No, this does not work. 
First in the current andriod(4.4), I am not allowed to use class from another library. 
Second, FileChooserActivity.EXTRA_SELECT_FOLDER does not event exist.
