### ISSUE TITLE
Filter file types

### ISSUE THREAD

**Issue by riyazMuhammad** [iPaulPro/aFileChooser#27]
First of all thanks for sharing this awesome piece of work :)

Hey Guys is there a way to filter file types in this library?

I mean I want to limit this chooser to select only pdf or doc files. 

Is there anything like this in here already ?

**Comment by iPaulPro** [comment]
Hey, sorry, I have not had time to devote to this library. There are a couple of pull requests with filter implementations that I have not tested.
