### ISSUE TITLE
Can anybody explain how can I use this in fragment?

### ISSUE THREAD

**Issue by LOG-TAG** [iPaulPro/aFileChooser#30]
I'm failed use this lib for fragments, child fragments . with call back!

**Comment by krischik** [comment]
Tried looking at the example? Looks pretty simple to me.

**Comment by krischik** [comment]
My last answer was to harsh. Sorry about that. The truth is: You don't. aFileChooser is an activity and is supposed to be used as one.

If you want to use `com.ipaulpro.afilechooser.FileListFragment` inside your own activity you have to duplicate most of the code in  `com.ipaulpro.afilechooser.FragmentActivity`. You have to decide for yourself it is worth it.
