### ISSUE TITLE
Disabling Google Drive from menu

### ISSUE THREAD

**Issue by ericlokness** [iPaulPro/aFileChooser#52]
I have been looking around but can't find an answer.  Is there an easy way to simply disabling Google Drive from displaying in the fileChooser?  That would be a much more simple solution if it is causing an error.

**Comment by svenoaks** [comment]
intent.putExtra(Intent.EXTRA_LOCAL_ONLY, true);

**Comment by ericlokness** [comment]
Thanks svenoaks!  This works great.  I even still have access to local DropBox files.

**Comment by myflashlab** [comment]
Thanks for the hint @svenoaks
